development:
  encoding: unicode
  pool: 5
  adapter: postgresql
  host: db
  username: huzaifa
  password: huzaifa8
  database: memee-dev

test:
  encoding: unicode
  pool: 5
  adapter: postgresql
  host: localhost
  username: postgres
  password: 1234
  database: memee-test

production:
  encoding: unicode
  pool: 5
  adapter: postgresql
  host: localhost
  username: deploy
  password: admin123

  database: memee-production

staging:
  encoding: unicode
  pool: 5
  adapter: postgresql
  host: localhost
  username: deploy
  password: admin123
  database: memee-staging
